//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisYonetimServisi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiparisYonetimEntities : DbContext
    {
        public SiparisYonetimEntities()
            : base("name=SiparisYonetimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TABLO_FIRMA> TABLO_FIRMA { get; set; }
        public virtual DbSet<TABLO_SIPARIS> TABLO_SIPARIS { get; set; }
        public virtual DbSet<TABLO_URUN> TABLO_URUN { get; set; }
    }
}
