//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisYonetimServisi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLO_URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TABLO_URUN()
        {
            this.TABLO_SIPARIS = new HashSet<TABLO_SIPARIS>();
        }
    
        public int ID { get; set; }
        public Nullable<int> FIRMAID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<int> STOK { get; set; }
        public decimal FIYAT { get; set; }
    
        public virtual TABLO_FIRMA TABLO_FIRMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLO_SIPARIS> TABLO_SIPARIS { get; set; }
    }
}
