//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisYonetimServisi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLO_SIPARIS
    {
        public int ID { get; set; }
        public Nullable<int> FIRMAID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public string MUSTERIAD { get; set; }
        public string MUSTERISOYAD { get; set; }
        public Nullable<System.DateTime> SIPARISTARIH { get; set; }
    
        public virtual TABLO_FIRMA TABLO_FIRMA { get; set; }
        public virtual TABLO_URUN TABLO_URUN { get; set; }
    }
}
