//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisYonetimServisi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLO_FIRMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TABLO_FIRMA()
        {
            this.TABLO_SIPARIS = new HashSet<TABLO_SIPARIS>();
            this.TABLO_URUN = new HashSet<TABLO_URUN>();
        }
    
        public int ID { get; set; }
        public string FIRMAAD { get; set; }
        public Nullable<bool> ONAYDURUM { get; set; }
        public Nullable<System.TimeSpan> IZBAS { get; set; }
        public Nullable<System.TimeSpan> IZBIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLO_SIPARIS> TABLO_SIPARIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLO_URUN> TABLO_URUN { get; set; }
    }
}
